#define IDD_PROPERTIES	1

#define IDC_PROPERTIES_SPECIFICSERVICEDECODING	100
#define IDC_PROPERTIES_ENABLEEMMPROCESS			101
#define IDC_PROPERTIES_INSTRUCTION_LABEL		102
#define IDC_PROPERTIES_INSTRUCTION				103
#define IDC_PROPERTIES_BENCHMARKTEST			104
#define IDC_PROPERTIES_INSTRUCTION_NOTE			105
#define IDC_PROPERTIES_CARDREADERNAME			110
#define IDC_PROPERTIES_CARDID					111
#define IDC_PROPERTIES_CARDVERSION				112
